import Head from 'next/head';
import Accomplishments from '../components/Accomplishments';
import Hero from '../components/Hero';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Little Lanae</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<Accomplishments />
		</div>
	);
}
