import Head from 'next/head';
import Hero from '../components/home/Hero';
import Accomplishments from '../components/home/Accomplishments';
import Footer from '../components/home/Footer';

export default function Home() {
	return (
		<>
			<div>
				<Head>
					<title>Little Lanae</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Hero />
				<Accomplishments />
				<div className='pb-10'></div>
			</div>
			<Footer />
		</>
	);
}
